CREATE TABLE ADMIN (
    code_admin CHAR(5) PRIMARY KEY,
    uname VARCHAR(255) NOT NULL,
    passwd VARCHAR(255) NOT NULL,
);

CREATE TABLE DATAS (
    num_datas INT PRIMARY KEY AUTO_INCREMENT,
    saisie_agent TEXT NOT NULL,
    saisie_client TEXT NOT NULL
);
CREATE TABLE DATAS_CLIENT (
    num_datas_client INT PRIMARY KEY AUTO_INCREMENT,
    datas TEXT NOT NULL,
    num_datas INT NOT NULL,
    FOREIGN KEY (num_datas) REFERENCES DATAS(num_datas),
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE CLIENT_ACCESS (
    token CHAR(50) PRIMARY KEY,
    num_datas_client INT PRIMARY KEY AUTO_INCREMENT,
    FOREIGN KEY (num_datas_client) REFERENCES DATAS_CLIENT(num_datas_client)
);
CREATE TABLE DATAS_AGENCE (
    num_datas_agence INT PRIMARY KEY AUTO_INCREMENT,
    datas TEXT NOT NULL,
    num_datas INT NOT NULL,
    FOREIGN KEY (num_datas) REFERENCES DATAS(num_datas),
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
);
CREATE TABLE AGENCE (
    code_agence CHAR(5) PRIMARY KEY,
    nom_agence VARCHAR(50) NOT NULL,
    icone_agence VARCHAR(255),
    num_datas INT NOT NULL,
    FOREIGN KEY (num_datas) REFERENCES DATAS(num_datas),
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    modification_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE AGENT (
    num_agent INT PRIMARY KEY AUTO_INCREMENT,
    code_agence CHAR(5) PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    passwd VARCHAR(255) NOT NULL,
    FOREIGN KEY (code_agence) REFERENCES AGENCE(code_agence),
    creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    modification_date DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE LOGS_CONNECTION (
    num_log INT PRIMARY KEY AUTO_INCREMENT,
    num_agent INT NOT NULL,
    FOREIGN KEY (num_agent) REFERENCES AGENT,
    ip_address VARCHAR(255) NOT NULL,
    client_info VARCHAR(255) NOT NULL,
    connection_date DATETIME DEFAULT AUTO_INCREMENT
);
CREATE TABLE LOGS_CLIENT_ACCESS (
    num_log INT PRIMARY KEY AUTO_INCREMENT,
    token CHAR(50) NOT NULL,
    FOREIGN KEY (token) REFERENCES CLIENT_ACCESS(token),
    ip_address VARCHAR(255) NOT NULL,
    client_info VARCHAR(255) NOT NULL,
    connection_date DATETIME DEFAULT AUTO_INCREMENT
);